### ISSUE TITLE
if ($a = value) { /* really what you want?*/ }

### ISSUE THREAD

**Issue by ErikvdVen** [juliomatcom/php-mistakes#3]
To be honest, I think this is not so bad:

```
if ($a = value) { /* really what you want?*/ }
```

Just run the body if the variable inside the if statement is "falsy" => 0, '', false, null ... 
I use it quite a lot instead of

```
$a = value;
if ($a) { 
    /* rest of the code*/ 
}
```

So why mention it as a mistake? Maybe it's not desirable in some cases, but I would definitely not say it's bad practice... 

Or I misunderstand your point, in that case some more explanation inside your `README.md` would be desirable 👍

**Comment by juliomatcom** [comment]
Hello @ErikvdVen , well noted
This doc is about common mistakes, the problem is not in the use of
`if ($a = value)` is  in using this syntax for test/comparing by mistake In the other hand could be considered a bad practice using an assignment and comparison in the same step, but more elegant too :+1:

**Comment by ErikvdVen** [comment]
Right, thanks for the clarification ;)

**Comment by juliomatcom** [comment]
thanks to you :facepunch:
